.TH BW 1 bw\-VERSION
.SH NAME
bw \- Black Window
.SH SYNOPSIS
.B bw
.RB [ \-f
.IR font ]
.RI slave
.RI [ arguments ...]
.PP
.SH DESCRIPTION
.B bw
is a simple terminal emulator.
.SH OPTIONS
.TP
.BI \-f " font"
defines the
.I font
to use when bw is run.
.SH SHORTCUTS
.TP
.B Break
Send a break in the serial line.
Break key is obtained in PC keyboards
pressing at the same time control and pause.
.TP
.B Ctrl-Shift-y
Paste from primary selection (middle mouse button).
.TP
.B Ctrl-Shift-c
Copy the selected text to the clipboard selection.
.TP
.B Ctrl-Shift-v
Paste from the clipboard selection.
.TP
.B Ctrl-Shift-i
Launch dmenu to enter a unicode codepoint and send the corresponding glyph
to bw.
.SH CUSTOMIZATION
.B bw
can be customized by modifying config.h and (re)compiling the source
code. This keeps it fast, secure and simple.
.SH DEPENDENCIES
libX11, libfontconfig, libfreetype
.SH AUTHORS
See the LICENSE file for the authors.
.SH LICENSE
See the LICENSE file for the terms of redistribution.
