.TH BW 1 bw\-VERSION
.SH NAME
bw \- Black Window
.SH SYNOPSIS
.B bw
.RB [ \-a ]
.RB [ \-i ]
.RB [ \-v ]
.RB [ \-f
.IR font ]
.RB [ \-g
.IR geometry ]
.RB [ \-w
.IR windowid ]
.RI slave
.RI [ arguments ...]
.PP
.SH DESCRIPTION
.B bw
is a simple terminal emulator.
.SH OPTIONS
.TP
.B \-a
disable alternate screens in terminal
.TP
.BI \-f " font"
defines the
.I font
to use when bw is run.
.TP
.BI \-g " geometry"
defines the X11 geometry string.
The form is [=][<cols>{xX}<rows>][{+-}<xoffset>{+-}<yoffset>]. See
.BR XParseGeometry (3)
for further details.
.TP
.B \-i
will fixate the position given with the -g option.
.TP
.BI \-w " windowid"
embeds bw within the window identified by
.I windowid
.SH SHORTCUTS
.TP
.B Break
Send a break in the serial line.
Break key is obtained in PC keyboards
pressing at the same time control and pause.
.TP
.B Ctrl-Shift-Page Up
Increase font size.
.TP
.B Ctrl-Shift-Page Down
Decrease font size.
.TP
.B Ctrl-Shift-Home
Reset to default font size.
.TP
.B Ctrl-Shift-y
Paste from primary selection (middle mouse button).
.TP
.B Ctrl-Shift-c
Copy the selected text to the clipboard selection.
.TP
.B Ctrl-Shift-v
Paste from the clipboard selection.
.TP
.B Ctrl-Shift-i
Launch dmenu to enter a unicode codepoint and send the corresponding glyph
to bw.
.SH CUSTOMIZATION
.B bw
can be customized by modifying config.h and (re)compiling the source
code. This keeps it fast, secure and simple.
.SH DEPENDENCIES
libX11, libfontconfig, libfreetype
.SH AUTHORS
See the LICENSE file for the authors.
.SH LICENSE
See the LICENSE file for the terms of redistribution.
